### ISSUE TITLE
Consider naming the system methods with the user-defined names in the source language

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/cdk_framework#12]
Right now we use a hard-coded name for system methods, for example `_azle_heartbeat`. We should consider using the actual name defined by the developer in the source code language.

**Comment by dansteren** [comment]
May be superseded by https://github.com/demergent-labs/cdk_framework/issues/38.

**Comment by dansteren** [comment]
I think we've decided to go the opposite route on this. We now just call these methods by their system name, e.g. "heartbeat", "init", "pre_upgrade", etc. They are no longer prefixed, but we also won't give them the user-defined names.
